### ISSUE TITLE
parquet support?

### ISSUE THREAD

**Issue by virtualluke** [red-data-tools/arrow-packages#1]
Do these builds come with parquet support (built against parquet-cpp) ?

**Comment by kou** [comment]
We need to improve parquet-cpp for the followings before we create parquet-cpp package:

  1. Support versioned shared library.
  2. Support [multiarch](https://wiki.debian.org/Multiarch/HOWTO).

Could you send pull requests to parquet-cpp to support them like I did for Apache Arrow? We can create parquet-cpp package after parquet-cpp is improved.

For supporting versioned shared library:

  * https://github.com/apache/arrow/pull/401

For supporting multiarch:

  * https://github.com/apache/arrow/pull/398
  * https://github.com/apache/arrow/pull/419

**Comment by kou** [comment]
I've added Apache Parquet C++ packages.
