### ISSUE TITLE
Components `main` not found

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/arrow-packages#11]
* Ubuntu

`sudo vi /etc/apt/sources.list.d/red-data-tools.sources`

```
Types: deb deb-src
URIs: https://packages.red-data-tools.org/ubuntu/
Suites: eoan
Components: main
Signed-By: /usr/share/keyrings/red-data-tools-archive-keyring.gpg
```

I changed the `main` to `universe`. Then it works.

**Comment by kou** [comment]
Thanks.
I've fixed and uploaded.
`apt update && apt upgrade` will fix.
