### ISSUE TITLE
Add Ubuntu 21.04

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/arrow-packages#24]
* Ubuntu 20.10 (Groovy Gorilla) reached end of life on 2021-07-22

**Comment by kou** [comment]
Done.

**Comment by kojix2** [comment]
Thanks!

**Comment by kojix2** [comment]
I'm sorry, but hirsute(21.04) doesn't seem to exist?
https://packages.red-data-tools.org/ubuntu/dists/
![image](https://user-images.githubusercontent.com/5798442/127141050-d6919934-94cf-4d82-b135-d8134c868a6e.png)

**Comment by kou** [comment]
Oh, sorry.
I've uploaded.

**Comment by kojix2** [comment]
Thanks!
