### ISSUE TITLE
End of distribution of libgr by red-data-tools

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/arrow-packages#28]
Since sciapp/gr distributes the official package, we are planning to end the distribution of the red-data-tools package. 
However, there are some problems with the official package of sciapp/gr.

First, there seems to be some kind of key problem and the repository is not added correctly.
* https://github.com/sciapp/gr/issues/142
* https://github.com/sciapp/gr/issues/143

Second, the shared library cannot be detected by `pkg-config`, so you need to set the environment variable `GRDIR`. 
This may be because the package distributed with sciapp/gr installs the files in a non-standard location on Linux.

Despite these few problems, I think it is preferable to improve the official package instead of the red-data-tools package.

**Comment by kou** [comment]
> Despite these few problems, I think it is preferable to improve the official package instead of the red-data-tools package.

I like this approach.

**Comment by kojix2** [comment]
Can you please end the distribution of GR?

**Comment by kou** [comment]
OK.
Should we remove existing packages? Or can we just stop distributing new packages?

**Comment by kojix2** [comment]
Probably the most correct way is to notify the end of the distribution in README.md. 
Then, after a few months, remove existing packages.

**Comment by kojix2** [comment]
However, I believe that few or no one actually uses the red-data-tools GR package. 
So I think we can simply stop the distribution of all the files.
Removing a mechanism that already exists does not take much time, but it does take a lot of emotional power.

**Comment by kou** [comment]
OK.
I've just removed `gr/` and descriptions in README.

**Comment by kojix2** [comment]
Thanks !!
