### ISSUE TITLE
Not finding libparquet-dev 1.3.1 for debian/ubuntu in the repositories

### ISSUE THREAD

**Issue by mikn** [red-data-tools/arrow-packages#6]
Hi!
I see you've updated your build tree to build 1.3.1, but I cannot find 1.3.1 in the repository. Is this intentional? :)

**Comment by kou** [comment]
We can't find the tag for 1.3.1 in apache/parquet repository.
And Apache Parquet C++ can't be built with Apache Arrow 0.8.0. We need the next Apache Parquet C++ release.

**Comment by mikn** [comment]
https://github.com/apache/parquet-cpp/commit/80196bcea536a32de9cb5cdc4e6e071c091986d5 this is the commit tagged with 1.3.1 - and I'm currently compiling 1.3.1 against Arrow 0.7.1, which seems to work fine :)

**Comment by kou** [comment]
It can't be found in cloned repository.

**Comment by xhochy** [comment]
@kou do you see anything special about that tag? This is not the first time that I heard this problem with 1.3.1 :(

**Comment by kou** [comment]
@xhochy I can find the tag by `git submodule deinit vendor/parquet-cpp && rm -rf .git/modules/vendor/parquet-cpp && git submodule update --init`. I don't know why I need to re-clone the repository...

By the way, it there any plan to release a new parquet-cpp version that supports Apache Arrow 0.8.0?

**Comment by xhochy** [comment]
We plan to release parquet-cpp 1.4 soon. Actually we would have already liked to have it released but some things got in the way. As the Thrift 0.11 release is breaking, we should release rather soon.

**Comment by kou** [comment]
Great!
I'll update deb/rpm packages when parquet-cpp 1.4 is released.

**Comment by kou** [comment]
I've uploaded packages for apache-parquet-cpp 1.4.0-rc1.
