### ISSUE TITLE
Why "--allow-insecure-repositories"?

### ISSUE THREAD

**Issue by cobbr2** [red-data-tools/arrow-packages#9]
I'm concerned about allowing insecure repos in general, and based on the settings you provide, I do have to do this *in general*, not just for this specific repo.  Why is this required?

Ubuntu user (14.04, 16.x); health care startup, so insecure components make us *very* concerned.

**Comment by kou** [comment]
Because we can't install packages from repository without its PGP key but we need to install its PGP key from the repository.

Another approach: https://wiki.debian.org/DebianRepository/UseThirdParty

We have a plan to migrate to the another approach.
